import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import Navigation from '@/components/organisms/Navigation';
import Footer from '@/components/organisms/Footer';
import React from 'react';
import cn from 'classnames';
import styles from './page.module.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, styles.wrapper)}>
        <Navigation />
        <div className={styles.contentWrapper}>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
