import type { Metadata } from 'next';
import Navigation from '@/components/organisms/Navigation';
import Footer from '@/components/organisms/Footer';
import React from 'react';
import Providers from './providers';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-full">
      <body className="min-h-full">
        <Providers>
          <Navigation />
          <div className="grid">
            <div className="max-w-[1024px]">
              {children}
            </div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
